/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public String getGreeting() {
    return "Hello world!";
  }

  public static void main(String[] args) {
    System.out.println("안녕안녕?!!");
    System.out.println("2020-09-09-09-09-09-09");
    System.out.println("어휴 배고파");
    System.out.println("점심 뭐먹지");
  }
}
